In [2]:
import cv2, time
import numpy as np

In [3]:
img = cv2.imread("opencv face1.jpeg", 1)

In [4]:
# img.size
# img.shape
#nimg = cv2.resize(img, (int(img.shape[1]/4), int(img.shape[0]/4)))

In [5]:
# Image Detection
# start here

# cascade classifier function loads pre-trained xml file to detect face
facedet = cv2.CascadeClassifier(cv2.data.haarcascades +"haarcascade_frontalface_default.xml")

# converts to grey image
greyimg = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [6]:
# detectMultiScale function detects the face from image and gives x,y,z,w as width and height of rectangle in which face is.
faces = facedet.detectMultiScale(img, scaleFactor = 1.05, minNeighbors = 5)
x, y, z, w = faces[0]

img = cv2.rectangle(img, (x, y), (x+z, y+w), (0, 255, 255), 2 )

In [7]:
# show the image
cv2.imshow("Face", img)

# waitKey with argument 0 will wait till any key is pressed
cv2.waitKey(0)

# close the wind
cv2.destroyAllWindows()

# end here

In [17]:
# face detection in video
# start here

# VideoCapture is function to capture video
video = cv2.VideoCapture(0)

while True:
    # video.read() captures video from camera, check is true if capture is allowed, frame is 1st image of video
    check, frame = video.read()
    
    # same code as image detection
    # from here
    faces = facedet.detectMultiScale(frame, scaleFactor = 1.25, minNeighbors = 5)
    for (x, y , w, h) in faces:
        frame = cv2.rectangle(frame, (x,y), (x+w, y+h), (0, 255, 255), 2)
#     x, y, z, w = faces[0]
    

#     frame = cv2.rectangle(frame, (x, y), (x+z, y+w), (0, 255, 255), 2 )
    # to here
    
    # showing each image
    cv2.imshow("video", frame)
    
    # waitKey(1) will return the key pressed and will wait till 1 millisecond
    key = cv2.waitKey(1)
    
    if key == ord('q'):
        break
        
        
video.release()
cv2.destroyAllWindows()

In [9]:
print(check)

True


In [10]:
print(frame)

[[[ 58  90  83]
  [ 58  92  85]
  [ 58  94  87]
  ...
  [ 51  76 122]
  [ 52  76 122]
  [ 53  77 123]]

 [[ 58  90  83]
  [ 56  90  83]
  [ 56  92  85]
  ...
  [ 50  75 121]
  [ 50  74 120]
  [ 51  75 121]]

 [[ 61  88  83]
  [ 57  86  81]
  [ 54  85  80]
  ...
  [ 48  71 119]
  [ 49  70 118]
  [ 51  72 120]]

 ...

 [[ 86  75  28]
  [ 86  75  28]
  [ 87  77  28]
  ...
  [ 77  66  55]
  [111 100  89]
  [126 115 104]]

 [[ 89  78  33]
  [ 86  75  30]
  [ 85  74  27]
  ...
  [ 84  67  62]
  [ 85  67  65]
  [117  99  97]]

 [[ 94  83  38]
  [ 87  76  31]
  [ 81  70  23]
  ...
  [ 90  73  68]
  [ 90  72  70]
  [ 89  71  69]]]
